### ISSUE TITLE
AWS Lambda, GCP Cloud Function 추가

### ISSUE THREAD

**Issue by MoohyunSong** [ddps-lab/serverless-container-performance-comparison#3]
1. Lambda, Cloud Function에 사용할 각 Container를 생성해야 합니다.
- 언어는 Python 3.11.3을 사용할 예정이며, tensorflow는 동일하게 사용할 예정입니다.
- Lambda는 AWS ECR, Cloud Function은 GCP Artifact Registry에 저장할 예정입니다.
- Lambda는 API Gateway (HTTP 1.1)을 통한 연결이 될 것이며, preprocessing된 데이터를 전송하여 event로 받아 처리하는 식으로 최대한 tfserving과 유사하게 구성할 예정입니다.
- Cloud Function은 사용해보지 않아 한번 들여다보고 최대한 유사한 방법으로 가능하도록 구성하겠습니다.

2. IaC 작업
- IaC를 통해 설정 조작을 간편하게 하여 실험을 원활하게 할 예정입니다.

3. AWS Lambda, GCP Cloud Function의 성능을 측정하기 위한 코드를 제작할 예정입니다. (현재는 CloudRun 측정만 자동화가 완료됨, 어렵지 않음.)

**Comment by MoohyunSong** [comment]
GCP Cloud Functions를 비교군에 포함할지에 관해 생각을 해보아야할 듯 합니다.

Cloud Functions 1세대의 경우, Code ZIP을 업로드하는 Lambda와 유사한 서비스이며,
Cloud Functions 2세대의 경우, 애초에 CloudRun과 동시에 생성되며(두가지 서비스 탭에서 모두 조회가 가능합니다.) 1세대와 달리 CloudRun의 모든 기능을 사용할 수 있습니다. 다른 점은 Code ZIP을 업로드해서 Cloud Run을 구성한다는 것 뿐이죠.
사실상 Cloud Run이 Cloud Functions을 대체하는 서비스라고 봐도 무방할 듯 합니다.
![image](https://github.com/ddps-lab/serverless-container-performance-comparison/assets/49053299/e93f49a9-8f52-4ed2-97e3-a2e1d6a94afb)

그래서 Cloud Run과 동일하지 않은 Cloud Function 1세대으로 IaC는 구성 자체는 모두 완료하였으나 (Commit은 아직 안함), mobilenet_v1 을 테스트할 땐 문제가 없었으나 bert model의 용량이 500MB를 넘어가 Cloud Function 1세대의 제한(500MB)를 넘어 비교가 불가능합니다.

제가 생각하는 대안은 아래와 같습니다.
1. 러닝 커브가 있을 수 있겠지만 Cloud Function을 제외하고 Azure Function을 비교군에 추가
(Customizing이 불가능한 AWS Lambda, Azure Functions와는 다르게 GCP Cloud Run을 사용하면 gRPC를 사용하는 등의 이점을 살릴 수 있다~~~ 같은 형식이 될 것 같습니다.) (단, Azure Functions도 gRPC를 지원할 수도 있으니 분석 필요 (아직 안찾아봄))
2. AWS Lambda와 Cloud Run만을 비교
3. 500MB 가 넘어가는 model(bert_imdb, distilbert_sst2)은 사용이 불가능하지만 그래도 Cloud Function 1세대를 성능 비교 제품군에 포함

**Comment by hyu-leeky** [comment]
오케이. 무현아 잘 분석했다. gcp 의 함수 실행환경 정책이 CloudRun 으로 넘어간다라고 파악이 되네. 논문에서도 그런 방향으로 접근이 가능할것 같아. 전통적인 FaaS 로 azure function 과 aws lambda 를 커스터마이즈가 가능한 것으로 gcp cloud run 으로 하는 아이디어 좋아보인다. 물론 azure 를 학습하는데 시간이 걸리겠지만, 얼른 해낼것 같아 ㅎㅎ
그런데 cloud run 으로 넘어가면 과금 모델이 확실히 바뀔텐데 gcp cloud functions 의 과금모델도 함게 바뀌는지에 대한 검토가 미리 한번 되기는 해야겠다.

**Comment by MoohyunSong** [comment]
모두 완료되었으므로 issue close 하겠습니다.
