### ISSUE TITLE
yolo_v5, distilbert_sst2 keras 사용 불가능 문제

### ISSUE THREAD

**Issue by MoohyunSong** [ddps-lab/serverless-container-performance-comparison#4]
- yolo_v5 model이 tensorflow keras로 완전하게 build 된 것이 아니라 predict 함수를 호출할 수가 없는 문제가 있음.
-> tensorflow에서 사용할 수 있는 pretrained model을 찾거나 다시 model을 train하고 사용할 필요가 있어보임.
- 기존 edge-inference에 작성된 코드가 난해하여 잘 모르겠지만, 대략 torch를 사용해서 build하여서 keras library를 사용할 수 없는 것으로 보임
 (tfserving에서는 문제없이 가능하나, tensorflow keras를 통해 predict를 하려는 과정이 현재 불가능 함.)

**Comment by MoohyunSong** [comment]
추가로 distilbert_sst2도 keras를 사용할 수 없어 Lambda(Lambda라긴 보단 Python tensorflow)에서 사용할 수 없는 문제가 확인되었습니다.
> [WARNING]	2023-05-14T14:25:14.910Z		SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory. | [WARNING] 2023-05-14T14:25:14.910Z SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.

keras의 savefile인 pb가 없는 문제입니다.

distilbert_sst2도 tfserving은 사용가능합니다.

**Comment by hyu-leeky** [comment]
yolo 와 nlp 쪽은 엣지 장비에서만 실험을 하기는 했구나. 우선 이쪽의 문제가 해결이 되기는 해야겠네. 목표가 dnn 모델 서빙인 만큼.
지금 상황이 tfserving 을 사용할 경우는 사용이 가능한데, 일반 파이썬에서는 안된다는 이야기인거지? 만약에 Keras 를 람다의 실행 이미지에 포함 시킨다면 어떻게 될까?

**Comment by MoohyunSong** [comment]
Lambda에 keras가 없는게 아닌,모델이 keras API를 지원하지 않는 문제라 다시 빌드하거나 tensorflow keras를 지원하는 pre trained모델을 찾아봐야할 듯 합니다.

**Comment by MoohyunSong** [comment]
yolo_v5의 경우, model.predict(preprocessed_data)가 아닌 model(preprocessed_data)를 통해 예측 작업을 수행할 수 있는 것으로 확인되는 것 같습니다.
그런데 yolo의 경우, 640/640 size를 input으로 받는데, 이걸 API Gateway에 POST로 전달하면 Request Entity Too Large가 나타나는 문제가 나타나 처리하지 못하는 상황입니다.
gzip 등의 솔루션을 도입하여 압축 후 전송할 필요가 있을까요?
그런데 yolo만 gzip을 적용하기에는 또 공정한 network latency를 측정할 수 없을 것 같아 나머지도 적용해야할 것 같아 고민입니다.

**Comment by hyu-leeky** [comment]
API Gateway 에서 POST 페이로드 사이즈가 10메가 까지는 되는걸로 아는데 이미지가 이것보다 큰건가? 만약에 그정도로 크다면 압축등을 해야 할수도 있겠네. gRPC 와의 비교에서 압축을 사용하지 않는다면 문제가 될수도 있겠다. REST, gRPC 비교시에.
yolo 와 다른 모델의 성능을 비교하지는 않을듯 해서 yolo 에서는 rest 건 grpc 건 무조건 압축을 사용한다면 그건 크게 문제는 안될것 같아.

**Comment by MoohyunSong** [comment]
확인해보니,
현재 preprocessing이 된 numpy array를 json에 넣어 post로 server에 전달하는데,
이 과정에서 yolo_v5는 input이 640/640이라 데이터 크기가 상당히 크게 나온 것을 확인할 수 있었습니다.
(약 30mb 가량)

추가적으로 기존 tfserving에서도 다시 확인해보니 grpc는 무리없이 전송되는데 비해, rest의 경우에도 데이터를 압축해서 보내지 않으면 request 요청이 너무 커 CloudRun에서도 거부하고(그림1), gzip으로 압축해서 보내도 응답 하는 데이터 shape가 1,25200,85 여서 아래와 같은 에러가 나타납니다.(그림2)
<img width="1131" alt="image" src="https://github.com/ddps-lab/serverless-container-performance-comparison/assets/49053299/2b2dfa36-7e93-4828-8b8d-fecec84d5f3e">
<img width="735" alt="image" src="https://github.com/ddps-lab/serverless-container-performance-comparison/assets/49053299/bb4ec759-72c0-476a-80b2-e717777498ef">

(기존 yolo를 benchmark하는 코드가 잘못되어 coco dataset이 아닌 imagenet 을 사용해서 보내는 착오가 있어 정상작동하는 issue였던 것으로 확인됩니다.)

**Comment by hyu-leeky** [comment]
무현아 그러면 지금까지는 이미지넷 데이터셋 (coco 보다 사이즈가 작은) 을 사용해서 큰 무리없이 동작이 되었고, 제대로된 코코 데이터셋을 사용시에는 입출력의 크기가 너무 커서 API Gateway 를 통해서는 제대로 서비스 하기 힘들다고 보는게 맞을까?

**Comment by MoohyunSong** [comment]
맞습니다.
gzip을 통해 lambda로는 가능하지만, tfserving으로는 불가능한 것이 확인됐습니다.
현재 lambda로는 추론을 진행한 뒤, output을 순수 추론시간으로 설정했기에 출력 데이터가 작아서 가능하지만,
tfserving의 경우 output이 predict 결과 tensor가 전달되어 데이터가 너무 커서 불가능한 것 같습니다.
이를 해결위한 방법으로는 yolo_v5 모델을 수정하여 predict를 진행하되, output을 수정해서 (predict 순수 추론시간을 출력하도록 한다던지)로 모델을 빌드하는 방법이 있을 것 같습니다.

**Comment by hyu-leeky** [comment]
오케이. 쉽지는 않겠네. 수업 있는듯 하니 마치고 점심먹고 한 2시즘에 간단히 이야기해볼까?

**Comment by MoohyunSong** [comment]
결론 : 
yolo_v5는 모델 교체 없이 predict를 사용할 수 있게 되었으나 기존 방법으로는 Lambda with API Gateway 환경에서 사용이 불가능하여 아래와 같은 방법으로 대체

기존 : preprocessed data (numpy array)를 직접 json에 실어서 api gateway를 통한 lambda에 전달
대체 : preprocessed data를 s3에 업로드 후, api gateway를 통해 lambda에 bucket_name과 key_name 전달 후, lambda에서 추론을 시행한 뒤, s3에 업로드 후 s3 업로드 한 key name을 return, return 된 key_name을 가지고 다운로드 하는 것 까지 측정
(preprocess data upload time + network latency included inference time + predict data download time) 3가지가 합쳐서 측정됩니다.

**Comment by MoohyunSong** [comment]
이 issue는 close 하겠습니다.
