### ISSUE TITLE
Azure에서의 Container 사용 옵션 비교

### ISSUE THREAD

**Issue by MoohyunSong** [ddps-lab/serverless-container-performance-comparison#7]
[Azure Docs](https://learn.microsoft.com/ko-kr/azure/container-apps/compare-options)
위 Docs를 보면, Azure에서 사용할 수 있는 Container Option을 보여주고 간단하게 비교하는게 있습니다.

저희가 봐야할 부분은, Azure Container Apps와 Azure Functions가 있습니다.

간단하게 요약하자면, Azure Container Apps는 GCP Cloud Run에 대응된다고 볼 수 있고,
Azure Functions는 AWS Lambda에 대응된다고 볼 수 있습니다.

Azure Container Apps
- AKS 기반으로 동작하는 완전 관리형 Container Service (GCP Cloud Run과 상당히 유사)
- Azure에서도 Fully-Mangaed Serverless Container Service로 소개하고 있음.
- 간단하게 생성 버튼을 눌러 확인 결과, Cloud Run처럼 HTTP 1.1/2 또는 TCP 직접 연결을 지원하여 tfserving을 구성할 수 잇을 것으로 보임.

Azure Functions
- Lambda와 동일하게 Code를 upload해도되고, Code와 Library 등이 완전하게 설치된 Container를 통해 실행할 수도 있음.

***
현재는 우선 Azure Functions는 비교군에 추가하기로 하였기에 작업중이긴 합니다.(배포 테스트 및 Lambda에 있었던 yolo_v5에 대응되게끔하는 작업만 남아있습니다.)  Azure Container Apps도 들여다 보는게 좋을까요?

**Comment by hyu-leeky** [comment]
오케이 무현아 잘했다. Azure Container Apps 는 안해도 될것 같아. 우선 컨테이너 분야 서비스에서는 aws, gcp, azure 중에 gcp 가 제일 뛰어나다는게 일반적으로 알려져 있거든. Azure 가 흉내는 낼수 있는데, GCP 보다 딱히 더 뛰어나고 그러지는 않을것 같아. 대표적으로 GCP Cloud Run 했다 정도만 해도 괜찮을것 같아.

**Comment by MoohyunSong** [comment]
AWS, GCP와 같이 vCPU나 RAM을 숫자로서 정의할 수 있는게 아닌, Azure Function의 경우 App Service Plan 이라는 것으로 Resource의 Limit을 정의할 수 있습니다.
[App Service Plan Overview](https://learn.microsoft.com/en-us/azure/app-service/overview-hosting-plans)
종류가 상당히 복잡한데, 종류 별 알아보는것은 일단 미루고 현재 1vCPU, 4GB RAM을 기준으로 최초 실험을 진행할 생각이니
PremiumV3 Tier의 P0v3 Size (1 vCPU, 4GB RAM)으로 진행하겠습니다.

**Comment by MoohyunSong** [comment]
#8 해결되었으므로 issue는 close 하겠습니다.
